name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    

jobs:
  build:
    name: build and test minishell
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: install
      run: make install
    - name: make check
      run: make check
    - name: test
      run: make test
    - name: unit
      run: make unit
    - name: save expected
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: *.txt
